### ISSUE TITLE
find shadow rules from txt file

### ISSUE THREAD

**Issue by molchanov1983** [optiz0r/acl-analyser#1]
Hello
Is it possible to  find shadow rules from txt file ?

 20 permit ipv4 any 153.143.8.0 0.0.3.255
 30 deny udp any host 229.17.27.41 eq 5060
 38 deny tcp any 56.214.152.54/28 eq www
If not may you know another library i can use for that?
Thanks

**Comment by optiz0r** [comment]
Blast from the past!
After reminding myself what this project actually does, no it cannot. All it does is take a set of objects and acls and formats them in a way that can be easily pasted into an excel template so you can more easily see what's going on. It doesn't implement any firewall logic so can't tell you anything about rule shadowing. I'm not aware of any other libraries that do this.

**Comment by molchanov1983** [comment]
Thanks
